name: bump-formula-pr
on:
  release:
    types: [released]
  pull_request:

jobs:
  homebrew-grafana:
    name: homebrew-grafana
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
      id: app-token
      with:
        app-id: ${{ secrets.ALLOYBOT_APP_ID }}
        private-key: ${{ secrets.ALLOYBOT_PRIVATE_KEY }}
        owner: grafana
        repositories: alloy,homebrew-grafana

    # These need to be hard-coded to the bot being used; ideally in the future
    # we can find a way to automatically determine this based on the token.
    - name: Setup Git
      run: |
        git config --global user.name "grafana-alloybot[bot]"
        git config --global user.email "879451+grafana-alloybot[bot]@users.noreply.github.com"

    - name: Get latest release
      uses: rez0n/actions-github-release@794c12f5e8d629e6ca329cf2e2daeb0f0ce6a3ce # main
      id: latest_release
      with:
        token: ${{ steps.app-token.outputs.token }}
        repository: "${{ github.repository }}"
        type: "stable"

    - name: Update Homebrew formula
      # if: 'steps.latest_release.outputs.release_id == github.event.release.id'
      uses: dawidd6/action-homebrew-bump-formula@v4
      with:
        # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
        token: ${{ steps.app-token.outputs.token }}
        # Optional, defaults to homebrew/core
        tap: grafana/grafana
        # Formula name, required
        formula: alloy
        # Optional, will be determined automatically
        # tag: ${{github.ref}}
        tag: v1.8.2
        # Optional, will be determined automatically
        # revision: ${{github.sha}}
        revision: 14b3fa4
        # Optional, if don't want to check for already open PRs
        force: false # true
        user_name: grafana-alloybot[bot]
        user_email: 879451+grafana-alloybot[bot]@users.noreply.github.com
      env:
        HOMEBREW_DEVELOPER: "1"
        HOMEBREW_GITHUB_API_TOKEN: ${{ steps.app-token.outputs.token }}
  
    # - name: Update Homebrew formula
    #   # if: 'steps.latest_release.outputs.release_id == github.event.release.id'
    #   run: |
    #     brew bump-formula-pr \
    #       --no-browse \
    #       --no-audit \
    #       --no-fork \
    #       --dry-run \
    #       --verbose \
    #       --debug \
    #       --url https://github.com/grafana/alloy/archive/refs/tags/v1.7.0.tar.gz \
    #       grafana/grafana/alloy
    #   env:
    #     HOMEBREW_DEVELOPER: "1"
    #     HOMEBREW_GITHUB_API_TOKEN: ${{ steps.app-token.outputs.token }}
